# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160915_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
