# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_key',
            field=models.CharField(default='AAAAAAAAA', max_length=140),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='url',
        ),
    ]
